hndrs/slack-spring-boot-starter

build.gradle, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/MockSlackClient.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/channel/MockChannelsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/chat/MockChatGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/chat/MockChatPostMessageMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/dialog/MockDIalogGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/oauth/MockOauthMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/chat/MockChatPostMessageUnitTests.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/chat/PostMessageResponseExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/chat/PostMessage.kt
=> test: test method groups

build.gradle, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/channels/ChannelsArchiveMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/channels/ChannelsCreateMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/channels/ChannelsInviteMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/implementation/group/channels/DefaultChannelCreateMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/implementation/group/channels/DefaultChannelInviteMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/implementation/group/channels/DefaultChannelMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/implementation/group/channels/DefaultChannelsArchiveMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/channel/MockChannelsArchiveMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/channel/MockChannelsCreateMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/channel/MockChannelsInfoMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/channel/MockChannelsInviteMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/channel/MockChannelsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/channels/MockChannelsArchiveUnitTest.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/channels/MockChannelsCreateUnitTest.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/channels/MockChannelsInfoUnitTest.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/channels/MockChannelsInviteUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/channels/ChannelsArchiveExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/channels/ChannelsCreateExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/channels/ChannelsInfoExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/channels/ChannelsInviteExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/channels/ChannelsListExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/channels/ChannelsArchive.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/channels/ChannelsCreate.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/channels/ChannelsInfo.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/channels/ChannelsInvite.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/channels/ChannelsList.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/chat/PostMessage.kt
=> feat: mock channels group

build.gradle, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/chat/ChatDeleteMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/implementation/group/chat/DefaultDeleteMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/chat/MockChatDeleteMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/chat/MockChatGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/chat/MockChatPostEphemeralMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/MockMethodTestHelper.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/chat/MockChatDeleteUnitTests.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/chat/MockChatPostMessageUnitTests.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/chat/ChatDeleteExtensions.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/chat/Delete.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/chat/PostMessage.kt
added postEphemeral extensions
added postMessage extensions
=> Tests: chat delete 

build.gradle, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/ApiCallMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/conversations/ConversationsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockChatConversationCreate.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/MockMethodTestHelper.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/Create.kt
=> docs: add conversations create kdoc

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/conversations/ConversationsCloseMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsCloseMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsMethodGroup.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/IntegrationTests.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/TestConfiguration.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/conversations/ConversationCloseFailureTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsClose.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsCreate.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsCloseUnitTests.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversation/ConversationsCloseExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/Close.kt
=> Issue 19 Implement Conversation Close

starter/slack-spring-boot-autoconfigure/src/main/kotlin/io/olaph/slack/broker/autoconfiguration/SlackBrokerAutoconfiguration.kt, starter/slack-spring-boot-autoconfigure/src/main/kotlin/io/olaph/slack/broker/autoconfiguration/SlackBrokerConfigurationProperties.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/BrokerAutoConfigurationTests.kt, starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/broker/CommandBroker.kt, starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/exception/SlackExceptionHandler.kt, starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/metrics/CommandMetrics.kt, starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/receiver/MismatchCommandReciever.kt, starter/slack-spring-boot/src/test/kotlin/io/olaph/slack/broker/broker/CommandBrokerTests.kt, starter/slack-spring-boot/src/test/kotlin/io/olaph/slack/broker/receiver/CommandNotFoundReceiverTest.kt
resolves #177 
Implemented a fallback receiver in case the command broker can not recognize a given command
Everything working as currently expected
This fallback receiver enables the later usage of command execution provided via command + parameters
=> Adds command mismatch receiver

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/conversations/ConversationsArchiveMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsArchiveMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsMethodGroup.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/conversations/ConversationArchiveTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsArchiveMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsArchiveUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationsArchiveExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/Archive.kt
Added Conversations.archive method, Slackclient-, testclient-methods & test extensions
closes: #37 
missing method
added missing method
=> Feat: Conversations.archive method

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/conversations/ConversationsKickMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConverstationsKickMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/conversations/ConversationsKickTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsKickMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/conversations/MockConversationsKickUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationKickExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/Kick.kt
conversations.kick is not implemented
missing conversations.kick method
closes #27
=> feat: conversations.kick

client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/im/MockImMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/im/MockImOpenMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/im/MockImOpenUnitTests.kt
mock im.open() is missing
added mock method & tests for im-open method
=> added Mock Im.open() method

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/conversations/ConversationsSetPurposeMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsSetPurposeMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/conversations/ConversationSetPurposeTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsSetPurposeMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsSetPurposeUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationsSetPurposeExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/SetPurpose.kt
conversations.setTopic is not implemented
conversations.setTopic is missing
closes #32
=> feat: conversations.setPurpose

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/conversations/ConversationsInfoMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsInfoMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsMethodGroup.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/conversations/ConversationsInfoTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsInfoMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsInfoUnitTests.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationsInfoExtensions.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/common/types/Channel.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/Info.kt
Added conversations. info method 
missing method
added conversations.info method, default implementation, mocks & tests, test extensions
=> Feat: Conversations.info method, test, extensions and mocks

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/conversations/ConversationsRenameMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsRenameMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/conversations/ConversationRenameTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsRenameMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsRenameUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationsRenameExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/Rename.kt
conversations.rename method is missing
added conversations.rename, tests, mock, test extensions
=> added conversations.rename method, mock, tests, test extensions

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/conversations/ConversationsSetTopicMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsSetTopicMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/conversations/ConversationSetTopicTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsSetTopicMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsSetTopicUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationsSetTopicExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/SetTopic.kt
=> add conversations setTopic

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/conversations/ConversationsJoinMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsJoinMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsMethodGroup.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/conversations/ConversationsJoinTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsJoinMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsJoinUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationsJoinExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/Join.kt
missing conversations.close implementation
closes #25
=> feat: conversations.join

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/conversations/ConversationsRepliesMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsRepliesMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/conversations/ConversationRepliesTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsRepliesMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/conversations/MockConversationsRepliesUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/common/ResponseMetaDataExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationsListExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationsMembersExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationsRepliesExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/UserConversationsExtensions.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/common/ResponseMetadata.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/List.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/Members.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/Replies.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/UserConversations.kt
=> Add conversations.replies

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/conversations/ConversationsHistoryMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsHistoryMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsMethodGroup.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/conversations/ConversationHistoryTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsHistoryMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsHistoryUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationsHistoryExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/ConversationsJoinExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/common/ResponseMetadata.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/History.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/conversations/Join.kt
Missing conversations.history method
added conversations.history method, mocks, tests, test extensions
=> added conversations.history method, mocks, tests, test extensions

client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsOpenMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/conversation/MockConversationsOpenUnitTest.kt
conversations.open mock methods are missing
mock methods for conversations.open with tests are not implemented
implemented mock methods and tests for conversations.open
=> feat: conversations.open mock, tests

CONTRIBUTING.adoc, README.adoc
added missing contribution guidelines
=> added contribution guidelines

starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/broker/InstallationBroker.kt
installation errors are not logged
installation error response is logged now
=> fix: log error on installation failure

README.adoc, client/slack-spring-api-client/build.gradle, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/SlackCommandExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/SlackCommand.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/SlackEvent.kt, samples/slack-spring-boot-starter-sample/src/main/resources/application.properties, starter/slack-spring-boot-autoconfigure/build.gradle, starter/slack-spring-boot-autoconfigure/src/main/kotlin/io/olaph/slack/broker/autoconfiguration/SlackBrokerAutoconfiguration.kt, starter/slack-spring-boot-autoconfigure/src/main/kotlin/io/olaph/slack/broker/autoconfiguration/SlackBrokerConfigurationProperties.kt, starter/slack-spring-boot-autoconfigure/src/main/kotlin/io/olaph/slack/broker/autoconfiguration/credentials/CredentialsProvider.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/BrokerAutoConfigurationTests.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/CredentialsProviderAutoConfigurationTests.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/InstallationAutoConfigurationTests.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/MetricsAutoConfigurationTests.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/SlackApiClientAutoConfigurationTests.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/TeamStoreAutoConfigurationTests.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/TestApplicationContext.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/credentials/CredentialsFileCredentialsProviderTests.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/credentials/CredentialsProviderChainTests.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/credentials/CredentialsProviderTests.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/credentials/SystemPropertyCredentialsProviderTests.kt, starter/slack-spring-boot/build.gradle, starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/configuration/EventArgumentResolver.kt, starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/configuration/InteractiveResponseArgumentResolver.kt, starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/configuration/SlackCommandArgumentResolver.kt, starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/security/VerificationMethodArgumentResolver.kt, starter/slack-spring-boot/src/test/kotlin/io/olaph/slack/broker/configuration/ArgumentResolverTestUtil.kt, starter/slack-spring-boot/src/test/kotlin/io/olaph/slack/broker/configuration/EventArgumentResolverTest.kt, starter/slack-spring-boot/src/test/kotlin/io/olaph/slack/broker/configuration/InteractiveResponseArgumentResolverTest.kt, starter/slack-spring-boot/src/test/kotlin/io/olaph/slack/broker/configuration/SlackCommandArgumentResolverTest.kt
=> add initial credentials provider chain

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersDeletePhotoMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUserMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersDeletePhotoMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersDeletePhotoMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersDeletePhotoMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/users/UsersDeletePhotoUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/UsersDeletePhotoExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/DeletePhoto.kt
closes #48 
missing method 
added users.deletePhoto method, mockmethod tests and extensions
=> feat: users.deletePhoto method

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersIdentityMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUserMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersIdentityMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersIdentityMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersIdentityMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/users/UsersIdentityUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/UsersIdentityExtensions.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/Identity.kt
added users.identity method, default implementation, mocks & test ext…ensions
closes: #192 
missing implementation 
added users.identity method, default implementation, mocks & test ext…ensions
=> feat: users.identity Method implementation

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersGetProfileMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUserMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersGetProfileMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersGetProfileMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersGetProfileMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/users/UsersGetProfileUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/UsersGetProfile.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/GetProfile.kt
added users.profile.get implementation
closes: #24 
added users.profile.get implementation, mocks, test extensions
=> added users.profile.get implementation

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersMethodGroup.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersSetProfileMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUserMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersSetProfileMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersSetProfileMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersSetProfileMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/users/UsersSetProfileUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/UsersSetProfileExtensions.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/SetProfile.kt
added users.set Profile method, tests & extensions
closes #26 
added users.setProfile method, tests, extensions & mocks
=> feat: users.setProfile

client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/im/MockImMarkMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/im/MockImMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/im/MockImMarkUnitTests.kt
tests & mocks were missing 
added im mark mocks and test
closes: #51 
added im mark mocks and test
=> feat: added im Mark mocks

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersMethodGroup.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersSetPresenceMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUserMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersSetPresenceMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersSetPresenceMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersSetPresenceMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/users/UsersSetPresenceUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/UsersSetPresenceExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/UserPresence.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/SetPresence.kt
users.setPresence is not implemented
missing users.setPresence Method
closes #31
=> feat: users.setPresence Method

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/im/ImHistoryMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/im/DefaultImHistoryMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/im/DefaultImMethodGroup.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/im/DefaultImHistoryMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/im/MockImHistoryMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/im/MockImMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/im/MockImHistoryUnitTests.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/im/ImHistoryExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/im/History.kt
missing im.history method
im.history not implemented
closes #49
=> feat: im.history

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/SlackClient.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsCreateMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsDisableMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsEnableMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsListMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsMethodGroup.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsUpdateMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/users/UsergroupsUsersListMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/users/UsergroupsUsersUpdateMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/DefaultSlackClient.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/users/DefaultUsergroupsUsersUpdateMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/usergroups/UsergroupsUsersUpdateMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/MockSlackClient.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/users/MockUsergroupsUsersUpdateMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/usergroups/UsergroupsUsersUpdateUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/users/UsergroupsUsersUpdateExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/users/Update.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/SlackApiClientAutoConfigurationTests.kt
Missing usergroups.users.update Method
usergroups.users.update Method missing
Created packages for usergroups and dummy classes (for future implementation)
closes #52
=> feat: usergroups.users.update Method

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsCreateMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupsCreateMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/usergroups/UsergroupsCreateMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsCreateMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/usergroups/UsergroupsCreateUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/UsergroupsCreateExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/UsergroupsExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/users/UsergroupsUsersUpdateExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/common/types/Usergroup.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/Create.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/users/Update.kt
usergroups.create method not implemented
missing usergroups.create method
closes #63
=> feat: usergroups.create

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersGetPresenceMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUserMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersGetPresenceMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersGetPresenceMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersGetPresenceMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/users/UsersGetPresenceUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/UsersGetPresenceExtensions.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/UserPresence.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/GetPresence.kt
implement users.getPresence Method
missing users.getPresence Method
closes #42
=> feat: users.getPresence

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersLookupByEmailMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/users/UsersMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUserMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersLookupByEmailMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/users/DefaultUsersLookupByEmailMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersLookupByEmailMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/users/MockUsersMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/users/UsersLookupByEmailUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/UsersLookupByEmailExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/users/LookupByEmail.kt
no users.lookupByEmail Method
users.lookupByEmail Method missing
closes #38
=> feat: users.lookupByEmail

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsListMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupsCreateMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupsListMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/usergroups/UsergroupsListMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsListMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/usergroups/UsergroupsListUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/UsergroupsCreateExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/UsergroupsExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/UsergroupsListExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/users/UsergroupsUsersUpdateExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/Create.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/List.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/Usergroup.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/users/Update.kt
usergroups.list not implemented
removed usergroups.users.update Usergroups-extension due to it being already present as seperate extension
closes #57
=> feat: usergroups.list

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsMethodGroup.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsUpdateMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupsUpdateMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/users/DefaultUsergroupsUsersUpdateMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/usergroups/UsergroupsUpdateMethodTest.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/usergroups/UsergroupsUsersUpdateMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsUpdateMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/users/MockUsergroupsUsersUpdateMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/usergroups/UsergroupsUpdateUnitTest.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/usergroups/UsergroupsUsersUpdateUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/UsergroupsUpdateExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/Update.kt
implemented usergroups.update Method
closes #56
=> feat: usergroups.update

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsDisableMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupsDisableMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/usergroups/UsergroupsDisableMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsDisableMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/usergroups/UsergroupsDisableUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/UsergroupsDisableExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/Disable.kt
implement usergroups.disable Method
closes #61
=> feat: usergroups.disable

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsMethodGroup.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/users/UsergroupsUsersListMethod.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/users/DefaultUsergroupsUsersListMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/usergroups/UsergroupsUsersListMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/users/MockUsergroupsUsersListMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/usergroups/UsergroupsUsersListUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/users/UsergroupsUsersListExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/users/List.kt
implement usergroups.users.list Method
closes #54
=> feat: usergroups.users.list

client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsEnableMethod.kt, client/slack-api-client/src/main/kotlin/io/olaph/slack/client/group/usergroups/UsergroupsMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/usergroups/DefaultUsergroupsEnableMethod.kt, client/slack-spring-api-client/src/test/kotlin/io/olaph/slack/client/spring/group/usergroups/UsergroupsEnableMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsEnableMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/group/usergroups/MockUsergroupsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/io/olaph/slack/client/test/group/usergroups/UsergroupsEnableUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/UsergroupsEnableExtension.kt, data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/group/usergroups/Enable.kt
implemented usergroups.enable Method
closes #59
=> feat: usergroups.enable

starter/slack-spring-boot-autoconfigure/src/main/kotlin/io/olaph/slack/broker/autoconfiguration/EvaluationReport.kt, starter/slack-spring-boot-autoconfigure/src/main/kotlin/io/olaph/slack/broker/autoconfiguration/SlackBrokerAutoconfiguration.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/io/olaph/slack/broker/autoconfiguration/EvaluationReportConfigurationTests.kt
The broker evaluation report will inform the user which beans have been registered after the startup of the application
closes #181
=> feat: broker evaluation report

data/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/common/types/Conversation.kt
Added missing fields to the conversation dto as described in #232 and https://api.slack.com/types/conversation
closes #232
=> added missing fields to conversation dto

.travis.yml, client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/MockSlackClient.kt
made mockresponseMethod group return correct class
=> changed return type

data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/ChannelsListExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/conversations/ConversationsRenameExtension.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/List.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/conversations/Rename.kt
=> Fix: added missing response_metadata

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/chat/ChatMeMessageMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/chat/DefaultChatMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/chat/DefaultMeMessageMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/chat/DefaultMeMessageMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/chat/MockChatMeMessage.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/chat/MockChatMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/chat/MockChatMessageUnitTests.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/ChatMeMessageExtensions.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/MeMessage.kt
added chat.meMessage implementation
=> chat.meMessage

.travis.yml, client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/chat/ChatUnfurlMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/chat/DefaultChatMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/chat/DefaultUnfurlMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/chat/DefaultUnfurlMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/chat/MockChatMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/chat/MockChatUnfurl.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/chat/MockChatUnfurlUnitTests.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/ChatUnfurlExtensions.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/Unfurl.kt
added chat.unfurl impl mock, tests and default implementatioN
missing chat.unfurl implementation
=> chat.unfurl

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/channels/ChannelsKickMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/channels/DefaultGetChannelKickMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelKickMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsKickMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/channels/MockChannelKickUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/ChannelKickExtension.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/Kick.kt
added channel kick method, mocks, tests, extensions and default impl
implementation missing
added implementation
=> channel.kick

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/channels/ChannelsUnarchiveMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelsUnarchiveMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelsUnarchiveMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsUnarchiveMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/channels/MockChannelsUnarchiveUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/ChannelsArchiveExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/ChannelsUnarchiveExtension.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/Archive.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/Unarchive.kt
missing channels.unarchive implementation
added channels.unarchive method, mocks, extensions, implementation
=> channels.unarchive

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/channels/ChannelsJoinMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelJoinMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelJoinMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsJoinMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/channels/MockChannelJoinUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/ChannelsJoinExtension.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/Join.kt
added channels.join method, implementation, mocks, extensions & tests
missing implemntation
=> channels.join

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/channels/ChannelsRenameMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelRenameMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelRenameMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsRenameMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/channels/MockChannelsRenameUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/Rename.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/Rename.kt
added tests, implementation, mocks & extensions
=> channels.rename

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/channels/ChannelsCreateMethod.kt, client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/channels/ChannelsMethodGroup.kt, client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/channels/ChannelsSetPurposeMethod.kt, client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/channels/ChannelsSetTopicMethod.kt, client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/channels/SetChannelsTopicMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelCreateMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelSetPurposeMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelSetTopicMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelCreateMethodTest.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelSetPurposeMethodTest.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelSetTopicMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsCreateMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsSetPurposeMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsSetTopicMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/channels/MockChannelsCreateUnitTest.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/channels/MockChannelsSetPurposeUnitTest.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/channels/MockChannelsSetTopicUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/ChannelSetTopic.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/ChannelsCreateExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/ChannelsSetPurpose.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/Create.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/SetPurpose.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/SetTopic.kt
added tests, implementation, extensions & dtos
implemented
=> channels.setTopic

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/channels/ChannelsLeaveMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelsLeaveMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelsMethodGroup.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/channels/DefaultChannelsLeaveMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsLeaveMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/channel/MockChannelsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/channels/MockChannelLeaveUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/Leave.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/Leave.kt
missing channel.leave implementation 
implemented methods
=> channels.leave

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/groups/GroupsInviteMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsInviteMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsArchiveMethodTest.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsInviteMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/auth/MockAuthTestMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsInviteMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsInviteUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Invite.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Archive.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Invite.kt
=> add groups invite method

README.adoc
added readme chpter on how to setup proxying
=> added proxy-chapter on readme

data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/InteractiveComponentResponseExtensions.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/PostEphemeralExtensions.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/InteractiveComponentResponse.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/channels/Mark.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/ParseType.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/PostEphemeral.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/PostMessage.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/Update.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/conversations/Replies.kt, samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/PingCommandReceiver.kt
Changed the properties which were still strings instead of instant
=> changed timestamps to instant datatype

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/groups/GroupsHistoryMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsHistoryMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsHistoryMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/MockSlackClient.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsHistoryMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsHistoryUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/History.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/History.kt
closes: #101 
addded groups.history method implementation with mocks, extensions & tests
=> added test, mocks, implementation, extensions

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/groups/GroupsUnarchiveMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsUnarchiveMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsUnarchiveMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsUnarchiveMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsUnarchiveUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Unarchive.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Unarchive.kt
closes: #113 
implemented groups.unarchive method, mocks, default implementation
=>  added groups.unarchive method

.github/PULL_REQUEST_TEMPLATE.md
added closes keyword to pr template
=> added closes keyword to pr template

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/groups/GroupsInfoMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsInfoMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsInfoMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsInfoMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsInfoUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Info.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Info.kt
closes: #102 
implemented default implementation, mocks, extensions
=> implemented groups.info method

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/groups/GroupsLeaveMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsLeaveMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsLeaveMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsLeaveMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsLeaveUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Leave.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Leave.kt
=> implemented groups.leave method

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/groups/GroupsKickMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsKickMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsKickMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsKickMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsKickUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Kick.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Kick.kt
=> implemented groups.kick

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/groups/GroupsMarkMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsMarkMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsMarkMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMarkMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMarkUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Mark.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Mark.kt
=> implemented groups.mark method

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/groups/GroupsListMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsListMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsListMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsListMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMethodGroup.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsListUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/List.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/List.kt
=> implemented groups.list method

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/groups/GroupsSetPurposeMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsSetPurposeMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsSetPurposeMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsSetPurposeMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsSetPurposeUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/SetPurpose.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/SetPurpose.kt
=> groups.setPurpose

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/groups/GroupsRenameMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsRenameMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsRenameMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsRenameMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsRenameUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Rename.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/Rename.kt
=> implemented groups.rename method

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/groups/GroupsSetTopicMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsSetTopicMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/groups/DefaultGroupsSetTopicMethodTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsSetTopicMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/groups/MockGroupsSetTopicUnitTest.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/SetTopic.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/groups/SetTopic.kt
=> implemented groups.setTopic method

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/reminders/RemindersInfoMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/reminders/DefaultRemindersInfoMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/reminders/DefaultRemindersListMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/reminders/DefaultReminderGroupTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/reminders/MockRemindersInfoMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/reminders/MockRemindersGroupTests.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/reminders/Info.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/reminders/List.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/reminders/Reminder.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/reminders/Info.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/reminders/List.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/reminders/common/Reminder.kt
closes: #93 
implemented reminders.info method, mockmethods dtos and extensions
=> reminders.info

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/reminders/RemindersCompleteMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/reminders/DefaultRemindersCompleteMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/reminders/DefaultReminderGroupTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/reminders/MockRemindersCompleteMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/reminders/MockRemindersGroupTests.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/reminders/Complete.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/reminders/Complete.kt
closes: #98 
implemented reminders.complete
=> reminders.complete

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/reminders/RemindersAddMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/reminders/DefaultRemindersAddMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/reminders/DefaultReminderGroupTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/reminders/MockRemindersAddMethod.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/reminders/MockRemindersGroupTests.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/reminders/Add.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/reminders/Reminder.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/reminders/Add.kt
closes: #100 
implemented reminders.add method
=> reminders.add

starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/store/FileTeamStore.kt, starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/store/TeamStore.kt
closes: #318 
incoming webhook should not be nullable
=> made incomingWebhook property optional

data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/InteractiveComponentResponseExtensions.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/MessageExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/PostEphemeralExtensions.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/InteractiveComponentResponse.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/common/Action.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/common/messaging/Block.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/common/messaging/Element.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/common/messaging/composition/Text.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/PostEphemeral.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/chat/PostMessage.kt, samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/rock_paper_scissors/RPSGameHandler.kt, samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/rock_paper_scissors/RockPaperScissorsCommandReceiver.kt, samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/rock_paper_scissors/RockPaperScissorsSubmissionReceiver.kt, samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/rock_paper_scissors/data/WEAPONS.kt, starter/slack-spring-boot/src/main/kotlin/com/kreait/slack/broker/configuration/InteractiveResponseArgumentResolver.kt
closes: #
added a slack command receiver that sends blocks back. 
Since the InteractiveComponentResponse is different when using blocks, i had to change some stuff there as well
=> modified interactive component response

data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/InteractiveComponentResponse.kt
made username in interactivecomponent#user nullable
=> fixed username

data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/InteractiveComponentResponse.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/common/Action.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/common/messaging/Attachment.kt, samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/send_button/SendButtonCommandReceiver.kt, samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/send_button/SendButtonComponentReceiver.kt, starter/slack-spring-boot/src/test/kotlin/com/kreait/slack/broker/broker/InteractiveComponentBrokerTests.kt
added missing id property to action & attachment
extended InteractiveComponentBrokerTests
=> added & extended tests & added id to action& attachment

.travis.yml, build.gradle.kts
added dokka gradle plugin, you can run now the task "dokka" under "documentation" in the gradle tab, to generate the html documentation out of the kotlin documentation
=> added dokka gradle plugin

guides/first_event_receiver.adoc, guides/first_slash_command_receiver.adoc, guides/quickstart_guide.adoc
removed newlines & changed receivers
=> mod guides

.travis.yml, build.gradle.kts
Notes:
Releases will be published by creating a Tag with that starts with "v"
Example Tag ```v1.0.0```
Depends On: https://issues.sonatype.org/browse/OSSRH-51804
=> Release repository prep

docs/slack-spring-boot-docs/src/main/asciidoc/getting-started.adoc
modified getting-started guide
=> modified getting-started

.travis.yml, build.gradle.kts, buildScripts/generate-release-docs.sh, buildScripts/generate-snapshot-docs.sh
=> test generate snapshot build script

buildScripts/generate-release-docs.sh, buildScripts/generate-snapshot-docs.sh
modified script, because the html5 folder was published as well
=> Modified scripts

docs/slack-spring-boot-docs/src/main/asciidoc/license.adoc
=> Added License.adoc

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/stars/StarsAddMethod.kt, client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/stars/StarsListMethod.kt, client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/stars/StarsMethodGroup.kt, client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/stars/StarsRemoveMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/stars/SpringStarsAddMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/stars/SpringStarsListMethod.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/stars/SpringStarsMethodGroup.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/group/stars/SpringStarsRemoveMethod.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/pins/SpringPinsMethodGroupTest.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/stars/MethodTests.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/group/stars/SpringStarsMethodGroupTest.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/pins/MockPinsAddMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/pins/MockPinsListMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/pins/MockPinsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/pins/MockPinsRemoveMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/stars/MockStarsAddMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/stars/MockStarsListMethod.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/stars/MockStarsMethodGroup.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/group/stars/MockStarsRemoveMethod.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/stars/PinsAddExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/stars/PinsListExtension.kt, data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/stars/PinsRemoveExtension.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/stars/Add.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/stars/List.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/group/stars/Remove.kt
fixed typos and documentation
closes: #80 #78 #76
=> Implement stars methods group

README.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/getting-started.adoc
modifications on documentation
=> Modified getting-started guide

data/slack-jackson-dto-test-extensions/src/main/kotlin/com/kreait/slack/api/contract/jackson/common/messaging/ElementExtensions.kt, data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/common/messaging/Element.kt, publish-meta.gradle.kts
=> Implement Multiselect Block

client/slack-api-client/src/main/kotlin/com/kreait/slack/api/group/respond/RespondMethodGroup.kt, docs/slack-spring-boot-docs/src/main/asciidoc/dev-features/kotlin-sample-extensions.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/dev-features/mock-client.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/index.adoc, guides/how_to_test.adoc, samples/slack-spring-boot-starter-sample/src/main/kotlin/com/kreait/slack/sample/ResponseCommandReceiver.kt, samples/slack-spring-boot-starter-sample/src/test/kotlin/com/kreait/slack/sample/ResponseCommandReceiverTest.kt
=> Extend Dev Features by Example

docs/slack-spring-boot-docs/build.gradle.kts, docs/slack-spring-boot-docs/libs/google-analytics.rb, docs/slack-spring-boot-docs/src/main/asciidoc/dev-features/credentials.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/dev-features/kotlin-sample-extensions.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/dev-features/mock-client.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/dev-features/teamstore.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/development-features.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/exceptions.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/features.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/features/client.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/features/commands.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/features/events.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/features/installation.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/features/interactive-components.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/features/metrics.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/features/security.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/getting-started.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/index.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/license.adoc, docs/slack-spring-boot-docs/src/main/asciidoc/starter.adoc
Added plugin that adds the google analytics code to the generated ref-doc files
=> added google analytics key

.travis.yml, client/slack-api-client/src/main/kotlin/com/kreait/slack/api/SlackClient.kt, client/slack-spring-api-client/src/main/kotlin/com/kreait/slack/api/spring/SpringSlackClient.kt, client/slack-spring-api-client/src/test/kotlin/com/kreait/slack/api/spring/SprinSlackClientTests.kt, client/slack-spring-test-api-client/src/main/kotlin/com/kreait/slack/api/test/MockSlackClient.kt, client/slack-spring-test-api-client/src/test/kotlin/com/kreait/slack/api/test/group/pins/MockPinsGroupTests.kt, starter/slack-spring-boot-autoconfigure/src/test/kotlin/com/kreait/slack/broker/autoconfiguration/SlackApiClientAutoConfigurationTests.kt
Mock Pins Method tests were forgotten in a previous PR
=> added MockPinsMethod-tests

data/slack-jackson-dto/src/main/kotlin/com/kreait/slack/api/contract/jackson/common/messaging/composition/Text.kt
Implementing function to find enum constant by its value.
closes: #442
=> Fixing Text.Type Deserializer
